// Generated by gencpp from file ros_service_assignment/RectangleArea.msg
// DO NOT EDIT!


#ifndef ROS_SERVICE_ASSIGNMENT_MESSAGE_RECTANGLEAREA_H
#define ROS_SERVICE_ASSIGNMENT_MESSAGE_RECTANGLEAREA_H

#include <ros/service_traits.h>


#include <ros_service_assignment/RectangleAreaRequest.h>
#include <ros_service_assignment/RectangleAreaResponse.h>


namespace ros_service_assignment
{

struct RectangleArea
{

typedef RectangleAreaRequest Request;
typedef RectangleAreaResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RectangleArea
} // namespace ros_service_assignment


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_service_assignment::RectangleArea > {
  static const char* value()
  {
    return "92e9c8f940da77dc3e1bc289f7dd146e";
  }

  static const char* value(const ::ros_service_assignment::RectangleArea&) { return value(); }
};

template<>
struct DataType< ::ros_service_assignment::RectangleArea > {
  static const char* value()
  {
    return "ros_service_assignment/RectangleArea";
  }

  static const char* value(const ::ros_service_assignment::RectangleArea&) { return value(); }
};


// service_traits::MD5Sum< ::ros_service_assignment::RectangleAreaRequest> should match 
// service_traits::MD5Sum< ::ros_service_assignment::RectangleArea > 
template<>
struct MD5Sum< ::ros_service_assignment::RectangleAreaRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_service_assignment::RectangleArea >::value();
  }
  static const char* value(const ::ros_service_assignment::RectangleAreaRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_service_assignment::RectangleAreaRequest> should match 
// service_traits::DataType< ::ros_service_assignment::RectangleArea > 
template<>
struct DataType< ::ros_service_assignment::RectangleAreaRequest>
{
  static const char* value()
  {
    return DataType< ::ros_service_assignment::RectangleArea >::value();
  }
  static const char* value(const ::ros_service_assignment::RectangleAreaRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_service_assignment::RectangleAreaResponse> should match 
// service_traits::MD5Sum< ::ros_service_assignment::RectangleArea > 
template<>
struct MD5Sum< ::ros_service_assignment::RectangleAreaResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_service_assignment::RectangleArea >::value();
  }
  static const char* value(const ::ros_service_assignment::RectangleAreaResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_service_assignment::RectangleAreaResponse> should match 
// service_traits::DataType< ::ros_service_assignment::RectangleArea > 
template<>
struct DataType< ::ros_service_assignment::RectangleAreaResponse>
{
  static const char* value()
  {
    return DataType< ::ros_service_assignment::RectangleArea >::value();
  }
  static const char* value(const ::ros_service_assignment::RectangleAreaResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_SERVICE_ASSIGNMENT_MESSAGE_RECTANGLEAREA_H
